---
kind: pipeline
type: docker
name: default

steps:
- name: phpunit
  pull: if-not-exists
  image: lorisleiva/laravel-docker
  volumes:
  - name: composer
    path: /drone/src/composer_cache
  environment:
    COMPOSER_HOME: /drone/src/composer_cache
  commands:
  - composer install
  - cp .env.example .env
  - composer install --no-interaction --prefer-dist --optimize-autoloader
  - php artisan key:generate
  - ./vendor/bin/phpunit
- name: PSR2
  pull: if-not-exists
  image: lorisleiva/laravel-docker
  commands:
  - phpcs --standard=PSR2 --exclude=Squiz.Scope.MethodScope,PSR1.Methods.CamelCapsMethodName app
- name: Code-Style
  pull: if-not-exists
  image: lorisleiva/laravel-docker
  volumes:
  - name: composer
    path: /drone/src/composer_cache
  environment:
    COMPOSER_HOME: /drone/src/composer_cache
  commands:
  - composer global require tightenco/tlint illuminate/support
  - ./composer_cache/vendor/bin/tlint

volumes:
- name: composer
  host:
    path: /composer
