---
kind: pipeline
type: docker
name: default

steps:
- name: composer install
  pull: if-not-exists
  image: lorisleiva/laravel-docker:7.4
  volumes:
  - name: composer
    path: /drone/src/composer_cache
  environment:
    COMPOSER_HOME: /drone/src/composer_cache
  commands:
  - cp .env.example .env
  - composer install --no-interaction --prefer-dist --optimize-autoloader
  - php artisan key:generate
- name: phpunit
  pull: if-not-exists
  image: lorisleiva/laravel-docker:7.4
  commands:
  - phpunit
- name: PSR2
  pull: if-not-exists
  image: lorisleiva/laravel-docker:7.4
  commands:
  - phpcs --standard=PSR2 --exclude=Squiz.Scope.MethodScope,PSR1.Methods.CamelCapsMethodName app

volumes:
- name: composer
  host:
    path: /composer
